version: '2'

services:
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #   - "3000:3000"
  rose:
    build:
      context: .
      dockerfile: rose.Dockerfile
      args:
      - AUTH_KEY=${authorized_keys}
    container_name: rose-station
    ports:
    - "2222:22"
