version: '2'

services:
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #   - "3000:3000"
  rose:
    build:
      context: .
      dockerfile: rose.Dockerfile
      args:
      - AUTH_KEY=${authorized_keys}
    container_name: rose-station
    ports:
    - "2222:22"
    depends_on:
    - mongodb
    volumes:
    - ${workspace_share}:/root/workspace
    networks:
    - app-network

  mongodb:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
      SERVICE_PASSWORD: service
    ports:
    - 27018:27017
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    - ${workspace_share}/db_data:/data/db
    networks:
    - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge